project:
    type: website
    output-dir: docs
    resources:
        - resume.pdf
        - cv.pdf
        - physics-paper.pdf
        - score.pdf
        - gre-score.pdf
        - drone.pdf
        - drone-cv.pdf
        - cv-latex.pdf
    render:
        - "*.qmd"
        - "!preposts/"
        - "!tinyml/"

website:
    title: "Marcobisky"
    site-url: https://marcobisky.github.io
    description: "Getting better every second!"
    open-graph:
        locale: en_US
    twitter-card:
        creator: "@Marcobisky77"
    comments:
        utterances:
            repo: Marcobisky.github.io
    navbar:
        right:
            - text: "Home"
              href: index.html
            - text: "CV"
              href: cv
            - text: "Blog"
              href: blog.html
            - text: "TinyML"
              href: tinyml/index.html
            - icon: rss
              href: blog.xml
    page-footer:
        left: "© Copyright 2025 Marcobisky."
format:
    html:
        theme: 
            light: [sandstone, _variables.scss]
            dark: [darkly, _dark-theme.scss]
        respect-user-color-scheme: true
        css: styles.css
        toc: true
        toc-expand: true
        self-contained: false
        grid: 
            margin-width: 350px
        page-layout: full
        number-sections: true
        number-depth: 4
        include-after-body: cloudflare-analytics.html
html-math-method: mathjax
reference-location: margin

execute:
    freeze: true