project:
    type: website
    output-dir: docs
    resources:
        - resume.pdf
        - cv.pdf
        - physics-paper.pdf

website:
    title: "Marcobisky"
    site-url: https://marcobisky.github.io
    description: "Technology and the Environment"
    open-graph:
        locale: en_US
    twitter-card:
        creator: "@Marcobisky77"
    comments:
        utterances:
            repo: Marcobisky.github.io
    navbar:
        right:
            - text: "Home"
              href: index.html
            - text: "CV"
              href: cv
            - text: "Blog"
              href: blog.html
            - icon: rss
              href: blog.xml
    page-footer:
        left: "© Copyright 2024 Marcobisky."
format:
    html:
        theme: [sandstone, _variables.scss]
        css: styles.css