---
config:
	theme: 'default'
	themeVariables:
		'git0': '#ffb700ff'
---
gitGraph
  commit id: "first"
  commit id: "rm DS_Store"
  commit id: "ad RV32-toolchain Mac"
  commit id: "update README"
  commit id: "Boot ROM and inst decoder d..."
  commit id: "GPIO output finished"
  commit id: "C env finished"
  commit id: "delay in C, gpio input start"
  commit id: "Preparing verilog version"
  commit id: "add some docs"
  commit id: "modified README"
  commit id: "Change mepc document"
