---
title: ""
author: ""
format:
  html: 
    number-sections: false
    other-links:
      - text: CV (PDF)
        href: database/generated/cv-lite/main.pdf
      - text: CV (Chinese PDF)
        href: database/generated/cv-lite-cn/main.pdf
      - text: Transcript with Grading Scheme
        href: score.pdf
      - text: Ranking Certificate
        href: rank.pdf
      - text: IELTS Report
        href: ielts-score.pdf
css: cv2.css
format-links: [pdf]
---

{{< include cv-web.qmd >}}


::: {.content-visible when-format="html"}

## ACADEMIC RECORD[^fullscore]

+----------+----------------------------------------------------------------------------+----------------------------------------+
| Year     | Subject                                                                    | Score (Full mark: 100)                 |
+==========+============================================================================+========================================+
| Year 1   | **Calculus I/II** <br> [\newline]{.print-only}                             | **91/92** <br> [\newline]{.print-only} |
|          | **Linear Algebra** <br> [\newline]{.print-only}                            | **84** <br> [\newline]{.print-only}    |
|          | **C Programming** <br> [\newline]{.print-only}                             | **95** <br> [\newline]{.print-only}    |
|          | **Physics I** <br> [\newline]{.print-only}                                 | **88** <br> [\newline]{.print-only}    |
+----------+----------------------------------------------------------------------------+----------------------------------------+
| Year 2   | **Physics II** <br> [\newline]{.print-only}                                | **96** <br> [\newline]{.print-only}    |
|          | **Signal and Systems** <br> [\newline]{.print-only}                        | **91** <br> [\newline]{.print-only}    |
|          | **Probability and Statistics** <br> [\newline]{.print-only}                | **92** <br> [\newline]{.print-only}    |
|          | Microelectronic Systems <br> [\newline]{.print-only}                       | 92 <br> [\newline]{.print-only}        |
|          | **Embedded Processors** <br> [\newline]{.print-only}                       | **95** <br> [\newline]{.print-only}    |
|          | **Circuit Analysis and Design** <br> [\newline]{.print-only}               | **95** <br> [\newline]{.print-only}    |
|          | Computer Network <br> [\newline]{.print-only}                              | 94 <br> [\newline]{.print-only}        |
|          | **Academic English** <br> [\newline]{.print-only}                          | **89** <br> [\newline]{.print-only}    |
+----------+----------------------------------------------------------------------------+----------------------------------------+
| Year 3   | Information Theory <br> [\newline]{.print-only}                            | 91 <br> [\newline]{.print-only}        |
|          | Principles of Communication <br> [\newline]{.print-only}                   | 95 <br> [\newline]{.print-only}        |
|          | **Digital Circuit Design** <br> [\newline]{.print-only}                    | **86** <br> [\newline]{.print-only}    |
|          | Machine Learning <br> [\newline]{.print-only}                              | 86 <br> [\newline]{.print-only}        |
|          | **Stochastic Signal Analysis** <br> [\newline]{.print-only}                | **82** <br> [\newline]{.print-only}    |
|          | **Communication Circuit Design** <br> [\newline]{.print-only}              | **92** <br> [\newline]{.print-only}    |
|          | **Electromagnetic Field and Microwave Technology** [\newline]{.print-only} | **88** <br>                            |
+----------+----------------------------------------------------------------------------+----------------------------------------+

: Core courses score (**GPA: 3.87**/4.00, **Avg: 87.94**/100, **rank: 2**/164)

[^fullscore]: I'm relatively confident in my understanding of the Boldface subjects.

::: {.content-visible when-format="html"}
See my detailed scores [here](score.pdf).
:::

:::


::: {.content-visible when-format="html"}

## INTERESTS

- **Classical Music Enthusiast🎻**: Concertmaster of 2nd Violin in UESTC symphony orchestra, votary of legendary composer Gustav Mahler and Johann Sebastian Bach.
- **Badminton Lover🏸**: Sports always refreshes me at any time.
- **Learning Everything🔍**: I believe everything is *learnable* by *First Principle Thinking* and *curiosity*.
- **Volunteer Work🤝**: Enjoy helping others. Over 15 hours of volunteering.

:::