### CMakeLists

#### 一般工作流与设计哲学

> 下面以这个工程模版为演示:

```{.css #lst-demoproj}
demo-proj/
├── build/                      # 所在目录绝对路径成为 CMAKE_BINARY_DIR 的值
│   ├── CMakeFiles/...
│   ├── math/...
│   ├── Makefile
│   └── ...
├── install/
│   ├── bin/
│   │   └── myapp               # 可执行文件
│   ├── include/                # 给使用者的头文件
│   │   ├── add.h
│   │   └── utils.h
│   └── lib/                    # 动态链接库 (myapp 必须要这些文件才能运行!)
│       ├── libmathlib.dylib
│       └── libutilslib.dylib
├── math/
│   ├── add.cc
│   ├── add.h
│   ├── utils.cc
│   ├── utils.h
│   └── CMakeLists.txt
├── main.cc
└── CMakeLists.txt              # 所在文件绝对路径成为 CMAKE_SOURCE_DIR 的值
```

- **Out-of-source build** 与 **In-source build**:
    - 上面的工程采用的是 Out-of-source build, 即把编译生成的文件都放在 `install/` 目录下, 源代码和编译生成的文件分开存放.
    - 如果是 In-source build, 则会把编译生成的文件和源代码文件混在一起, 不推荐:

        ```css
        demo-proj/
        ├── main.cpp
        ├── Makefile
        └── myapp
        ```

- 工作流:

    ```bash
    rm -rf build && mkdir build
    cd build
    cmake ..                                            # 配置阶段
    make                                                # 构建阶段
    cd .. && cmake --install build --prefix install     # 安装阶段: 生成 install/ 目录, 没有 prefix 则默认安装到 /usr/local/ (要 sudo)
    ```

    - **配置阶段**:
        - 一般会在 `build/` 目录下运行: `cmake ..` 而不是在 CMAKE_SOURCE_DIR 目录下运行 `cmake .`!
        - 仅配置阶段生效的命令要格外注意! 配置完了改变文件不重新 `cmake ..` 的话是不会生效的!
    - **构建阶段**
    - **安装阶段**

- **CMake built-in variables 内置变量**: 不能看作普通的变量! CMake 中会自动利用和管理这些变量, 比如 `CMAKE_MODULE_PATH` 这个宏能告诉 CMake 去哪里找文件.
    - `CMAKE_SOURCE_DIR`: 顶层 `CMakeLists.txt` 所在目录, 比如 `demo-proj/`.
    - `CMAKE_BINARY_DIR`: `cmake ..` 命令运行的根目录, 一般是 `demo-proj/build/`.
    - `CMAKE_CURRENT_SOURCE_DIR`: **当前** `CMakeLists.txt` 所在目录, 可以是顶层也可以是非顶层 (比如 `demo-proj/math/`).
    - `CMAKE_CURRENT_BINARY_DIR`: **当前** `CMakeLists.txt` 镜像到的 build 目录 (比如 `demo-proj/build/math/`).

#### CMakeLists 作为计算机语言

> 下面的命令都写在 `CMakeLists.txt` 里面, 并用: `cmake -P CMakeLists.txt` 运行.

> **String 字符串**: CMake 中的唯一类型!

- 基本操作:

    ```cmake
    # 赋值, 只有 string!
    set(A 123)          # A = "123"
    set(MY_LIST a b c)  # MY_LIST = "a;b;c", 还是字符串, 只不过自动用分号隔开了. 
                        # 不等价于 set(MY_LIST "abc"), 等价于 set(MY_LIST "a;b;c")
    # 打印
    message(A)          # 输出: A (没有自动解引用! 同 message("A"))
    message(${A})       # 输出: 123
    message(STATUS ${MY_LIST})  # 输出: -- abc (STATUS 表示这是状态信息, 会有 -- 前缀, 可选项还有 WARNING, ERROR)
    message("${MY_LIST}")       # 输出: a;b;c (用引号防止分号被忽略! 一般都用这种)

    # 字符串操作:
    # 追加字符
    list(APPEND A 4)
    list(APPEND MY_LIST de)
    message(${A})         # 输出: 1234
    message("${MY_LIST}") # 输出: a;b;c;de
    # 过滤字符
    set(MY_SRCS main.c utils.c main_test.c utils_test.c)
    list(FILTER MY_SRCS EXCLUDE REGEX "_test\\.c$")  # 过滤掉所有以 _test.c 结尾的文件
    message("${MY_SRCS}")  # 输出: main.c;utils.c
    # 替换字符
    string(REPLACE ".c" ".o" MY_OBJS "${MY_SRCS}")
    message("${MY_OBJS}")  # 输出: main.o;utils.o
    ```

- MACRO

    ```cmake
    # MACRO (纯文本展开!)
    macro(my_macro x y)
        message("x=${x}, y=${y}")
        set(X 100)
    endmacro()

    set(X 1)
    message(${X})       # 输出: 1
    my_macro(10 20)     # 输出: x=10, y=20
    message(${X})       # 输出: 100
    ```

- FUNCTION

    ```cmake
    # FUNCTION
    function(f a b)                 # f: 函数名. a,b: 形参
        message("a=${a}, b=${b}")
        message(${ARGC})            # 参数个数, 是全局变量!
        message(${ARGV})            # 所有参数列表, 是全局变量!
        message(${ARGV0})           # 第0个参数, 是全局变量! 同理有 ARGV1, etc.
        message(${ARGN})            # 额外参数列表, 是全局变量!
        set(X 200)
    endfunction()

    set(X 2)
    f(q ww e r t)                   # 输出: a=q, b=ww
                                    #       5
                                    #       qwwert
                                    #       q
                                    #       ert
    message(${X})                   # 输出: 2 (函数内修改不影响外部变量)
    ```


    - `cmake_parse_arguments()`: 解析命令行参数

        ```cmake
        function(test_parse)    # test_parse 函数名, 暂时不写参数
            # 1. 定义三类参数名, 这三种参数要严格遵循下面的顺序:
            set(aa AA)          # bool param
            set(bb BB)          # single value param
            set(cc CC1 CC2)     # multi values param

            # 2. 解析参数
            cmake_parse_arguments(MYPREFIX  # 表示在所有的宏变量前加 MYPREFIX_ 前缀
                "${aa}"                     # 匹配 AA
                "${bb}"                     # 匹配 BB
                "${cc}"                     # 匹配 CC1 CC2 CC3
                ${ARGN}                     # 匹配未匹配的参数
            )
            # 如果要忽略某个参数比如 bb, 一定要用 "" 代替而不能忽略:
            # cmake_parse_arguments(MYPREFIX "${aa}" "" "${cc}" ${ARGN})

            # 3. 打印结果
            message("${MYPREFIX_UNPARSED_ARGUMENTS}")   # 这个宏由 CMake 定义, 名字是固定的
            message("AA = ${MYPREFIX_AA}")
            message("BB = ${MYPREFIX_BB}")
            message("CC1 = ${MYPREFIX_CC1}")
            message("CC2 = ${MYPREFIX_CC2}")
        endfunction()

        # 4. 调用函数
        test_parse(
            test1 test2                     # test1 和 test2 会在未匹配参数中
            AA test3                        # test3 会在未匹配参数中
            BB main.cpp test4               # test4 也会在未匹配参数中
            CC1 inc include CC2 src test5   # test5 会在 CC2 中!
        )
        ```

        输出:

        ```bash
        test1;test2;test3;test4
        AA = TRUE
        BB = main.cpp
        CC1 = inc;include
        CC2 = src;test5
        ```

- 引入 Macro/Function

    ```cmake
    include(cmake/utils.cmake)
    # 可以使用 cmake/utils.cmake 里面定义的 Macro/Function
    ```
    - 告诉 CMake 去哪里找文件: 通过增加 `CMAKE_MODULE_PATH` 这个宏.

        ```cmake
        list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake")
        include(utils)  # 不是 utils.cmake!
        # 可以使用 cmake/utils.cmake 里面定义的 Macro/Function
        ```

- 分支

    ```cmake
    # 分支
    set(MY_FLAG ON)         # 相当于 True, ON 也可以换成: 1, YES, TRUE, Y
    if(MY_FLAG)
        message("true")     # 输出: true
    else()
        message("false")    # 不会执行
    endif()
    ```
    - 在 `if()` 括号里面的还有很多常见判断 (遇到了知道什么意思就行), 比如:
    
        ```cmake
        if(3 GREATER 2)         # 比较运算: GREATER, LESS, EQUAL, etc.
        if(DEFINED VAR)         # 变量是否定义
        if(EXISTS "${CMAKE_SOURCE_DIR}/test.cc")    # CMAKE_SOURCE_DIR 是 CMakeLists.txt 所在目录
        ```

#### CMake Built-in Commands

- 命令的参数顺序: **子命令 + 输入/变量 + 输入/变量**. 以 `file()` 为例:

    ```cmake
    file(GLOB MY_CSRCS *.c)     # GLOB (Global pattern matching): 子命令
                                # MY_CSRCS: 定义了一个变量
                                # *.c: 表示收集所有的 .c 文件
    ```

- `file()`: 文件操作

    ```cmake
    file(READ version.txt VERSION)          # 读取 version.txt 并定义到变量 VERSION
    file(WRITE output.txt "Hello World")    # 写入文件
    file(STRINGS params.json CONTENT)       # 将 params.json 的内容读到 CONTENT 变量 (每行之间的换行符会被替换为分号)
    file(COPY)
    file(MAKE_DIRECTORY ${CMAKE_BINARY_DIR}/output) # 创建目录
    file(REMOVE temp.txt)                   # 删除文件
    file(GLOB MY_CSRCS *.c *.cpp *.cc)      # 收集当前目录所有符合模式的文件名到变量 MY_CSRCS
    file(GLOB_RECURSE MY_SRCS src/*.c)      # src/ 的子目录中的 .c 也算 (仅配置阶段生效, 不建议使用)
    file(RELATIVE_PATH MY_REL_PATH /a/b/c /a/b/e/f.json)   # MY_REL_PATH = ../e/f.json
    ```

    - 模版文件: `configure_file()` 读入一个模版文件 `x.in`, 用当前 CMakeLists 中有的变量替换 `x.in` 中的变量然后输出到指定文件, 比如用以下工程结构:

        ```css
        .
        ├── CMakeLists.txt
        ├── hello.cc.in
        └── hello.cc            /* 也可以不创建, 自动生成 */
        ```
        
        ```{.cpp filename="hello.cc.in" @lst-helloccin}
        #include <iostream>
        int main() {
            std::cout << "Hello, ${NAME}!" << std::endl;
            return 0;
        }
        ```

        ```{.cmake filename="CMakeLists.txt" @lst-cmakelists}
        # 定义一个变量
        set(NAME World)

        # 用模板生成真实文件
        configure_file(
            hello.cc.in   # 输入模板
            hello.cc      # 输出文件
        )
        ```

        运行后:

        ```{.cpp filename="hello.cc" @lst-hellocc}
        #include <iostream>
        int main() {
            std::cout << "Hello, World!" << std::endl;
            return 0;
        }
        ```


- 模版工程 @lst-demoproj 中的文件细节:

```{.cpp filename="demo-proj/main.cc" #lst-maincc}
{{< include src/cmake/demo-proj/main.cc >}}
```

```{.cmake filename="demo-proj/CMakeLists.txt" #lst-cmakelistsdemo}
{{< include src/cmake/demo-proj/CMakeLists.txt >}}
```

::: {layout-ncol=2}
```{.cpp filename="demo-proj/math/add.cc" #lst-addcc}
{{< include src/cmake/demo-proj/math/add.cc >}}
```

```{.cmake filename="demo-proj/math/add.h" #lst-addh}
{{< include src/cmake/demo-proj/math/add.h >}}
```
:::

::: {layout-ncol=2}
```{.cpp filename="demo-proj/math/utils.cc" #lst-utilscc}
{{< include src/cmake/demo-proj/math/utils.cc >}}
```

```{.cmake filename="demo-proj/math/utils.h" #lst-utilsh}
{{< include src/cmake/demo-proj/math/utils.h >}}
```
:::

```{.cmake filename="demo-proj/math/CMakeLists.txt" #lst-cmakelistsmath}
{{< include src/cmake/demo-proj/math/CMakeLists.txt >}}
```


### Makefile

- 格式:

    ```makefile
    target: prerequisites
        recipe
    ```

- 缺省规则

    ```makefile
    .DEFAULT_GOAL := all
    all: ...
    ```

- 伪规则

    ```makefile
    .PHONY: all clean
    ```

- Append:

    ```makefile
    CFLAGS += -Wall -O2
    ```

- 改后缀名:

    ```makefile
    SRCS_ASM = start.S
    OBJS = $(SRCS_ASM:.S=.o)
    ```

- 冒号前面和后面:

    ```makefile
    %.o : %.c
        $(CC) $(CFLAGS) -c $< -o $@
    ```

    - `%` 为通配符, 意思是每当你需要一个 `.o` 文件, 并且当前目录下有对应的 `.c` 文件时, 就用下面的命令来生成它
    - `$<`: 第一个依赖文件
    - `$@`: 目标文件
    - `$^`: 所有依赖文件
    - `$?`: 所有比目标文件新的依赖文件

- 在 Makefile 里面调用 `make`: 建议用 `$(MAKE)` (不需要定义直接有).

### Bazel

#### Advantages

- **安装依赖方便**
    - Bazel 有很多第三方库. 比如硬件开发要用的 `verilator`, 引用库后 `bazel build` 会自动下载这个工具链的可执行文件到当前目录下的比如 `./bazel-bin/external/verilator` 位置! 极其方便!

#### 基本概念与设计哲学

- **Rule 规则**: 

#### Usage

- **规则复用**:
    - `rules/` 下面放很多类似 Python 语言的 `.bzl` 规则函数库, 定义了如何从指定的输入生成目标文件, 可以在 `BUILD` 文件中引用 (`load()`) 这些函数, 然后调用它们.
    - 用比如 `load("@rules_hdl//verilator:defs.bzl", "verilator_cc_library")` 来引用第三方规则库 (rules_hdl github 仓库位置需要先声明).
    - `genrule`: 如果要在 `BUILD` 里面直接用命令行生成文件 (而不是引用 `rules/` 中的规则), 可以用 `genrule`:

        ```python
        genrule(
            name = "generate_file",
            srcs = ["input.txt"],
            outs = ["output.txt"],
            cmd = "cp $(SRCS) $(OUTS)",
        )
        ```