---
title: "EDA: 3D IC Placement"
---

## DREAMPlace Naming Manual 命名法

- `flat_netpin`, `netpin_start`: 见下方 pin-list 表示法 (CSR).

<!-- ----------------------------------------- -->
::: {.callout-note icon=true collapse=true}
## pin-list 表示法 (CSR)

我们的目标是设计一种储存 net-pin 对应关系的数据结构. 首先将所有 net 的所有 pin 安排上**全局索引**. E.g., 假设我们有 $3$ 个 net, 分别包含以下 pin (用全局索引表示):

```plain
net0 = [p1, p7, p3]
net1 = [p8, p2]
net2 = [p6, p5, p9, p4]
```

将上述 pin 展平来定义 `flat_netpin` 数组:

```plain
flat_netpin = [p1, p7, p3, p8, p2, p6, p5, p9, p4]
``` 

当然实际上我们会用 pin 的全局索引值来表示 pin:

```cpp
int flat_netpin[] = {1, 7, 3, 8, 2, 6, 5, 9, 4};
```

再定义 `netpin_start` 数组来记录每个 net 的起始位置:

```cpp
int netpin_start[] = {0, 3, 5, 9};
```

这样, net-pin 对应关系就编码在了两个数组 `flat_netpin` 和 `netpin_start` 中. 这种方法 **节省内存空间、方便 GPU 并行处理**.
:::
<!-- ----------------------------------------- -->

### Database 数据库

#### Place2D

- **Index 规则**: `layer = 0` (top), `1` (bottom), `2` (HBT).

- `xl(0)`, `yl(0)`, `xh(0)`, `yh(0)`: Top die 可放置 cell 的区域 (xlow, ylow, xhigh, yhigh).
    - `xl(2)`, `yl(2)`, `xh(2)`, `yh(2)`: 中间层放置 bonding terminal 的区域 (有 padding).

- `raw_xl(0)`, `raw_yl(0)`, `raw_xh(0)`, `raw_yh(0)`; `gp_xl(0)`, `gp_yl(0)`, `gp_xh(0)`, `gp_yh(0)`: 跟上面没区别 (就是复制).

- `die_area`: Die 面积 (> (`xh(0)`-`xl(0)`) * (`yh(0)`-`yl(0)`) ).

- `site_width`, `row_height`: Site 的宽度和高度.

- `num_physical_nodes`：原始 placedb 里的所有 node 数 (movable + 固定 + IO + HBT), 还没加 filler.

- `num_movable_nodes`：所有 movable nodes 数 (对 2D 情形就是 num_nodes - num_terminals).

- `num_total_all_nodes`：按 pin map 数出来的 node 数, 要求和 `num_movable_nodes` 一致 (有 assert).

- `num_nets` / `num_pins`：普通意义上的 nets / pins 数目.

- `num_movable_pins`：可动节点 + IO 节点上的 pin 总数 (因为 IO 也要参与布线 / timing).

- `num_bonding_terminals`：插入的 HBT 个数.

#### ops/partition

- `node_partition_mask = [1, 1, 0, 0]`: 表示前两个 node 在 bottom die, 后两个在 top die.

- `net_bonding_terminal_mask = [0, 1, 0]`: 表示只有第二个 net 跨层 (需要 HBT).

## Environment Setup

<!-- ----------------------------------------- -->
::: {.callout-note icon=true collapse=true}
## MacOS (未成功)

Clone 仓库:

```bash
git clone <repository-url>
git submodule update --init --recursive
```

创建 `Python` 环境:

```bash
conda create -n cupid python=3.9
conda activate cupid
pip install torch torchvision torchaudio
pip install pyunpack patool matplotlib cairocffi pkgconfig scipy
pip install "numpy>=1.15.4,<2.0"
pip install setuptools
mkdir -p build
cd build
```

安装 `openMP` 支持:

```bash
brew install libomp
brew --prefix libomp
export OpenMP_ROOT=/opt/homebrew/opt/libomp
export OpenMP_CXX_FLAGS="-Xpreprocessor -fopenmp -I/opt/homebrew/opt/libomp/include"
export OpenMP_CXX_LIB_NAMES="omp"
export OpenMP_omp_LIBRARY=/opt/homebrew/opt/libomp/lib/libomp.dylib
```

安装 `bison`:

```bash
brew install bison
```
:::
<!-- ----------------------------------------- -->


