---
title: "Resources 学习资料汇总"
---

> 以下是我学习过程中发现的比较好用的资料. 注意这里只是大概的分类, 同一个资料可能会在多个话题下有帮助, 但这里只列出一次 (在对我帮助最大的话题下), 顺序大致遵循学习规律.

> ★★☆☆☆ **does not represent they are bad! Conversely, they are amazing! Only because I take away fewer information from them.**

<!-- Copy this: ★★★★★☆☆☆☆☆ -->

## CPU

- [**An Introduction to Computing Systems Yale Patt**](https://icourse.club/uploads/files/96a2b94d4be48285f2605d843a1e6db37da9a944.pdf): ★★★★★ 如果你大一想认真学一下计算机组成原理, 信我的, 读它准没错 ([wetABQ](https://sdl.moe) 大佬推荐的).
    - 本书详细讲了一个简单的 16-bit [LC-3](https://en.wikipedia.org/wiki/Little_Computer_3) CPU 的设计, 包括指令集、汇编语言、机器语言、微架构等内容. 

- [**Bilibili: RISCV-MCU**](https://www.bilibili.com/video/BV1QXnoexEi5?spm_id_from=333.788.videopod.sections&vd_source=42579e22289b6144ba0b2bdcf99834e3): ★★★★★ 一个基于 Digital 和 verilog 的 RISC-V CPU 仿真教程, 讲得非常好, 强推!
    - 本人基于这个项目做了一个 [**my-riscv**](https://github.com/Marcobisky/my-riscv).

- [**The "Basic" Pipelined CPU**](https://www.cs.emory.edu/~cheung/Courses/355/Syllabus/7-pipeline/basic.html): ★★★★★ 讲了 CPU 流水线 5 个阶段的工作原理.
    - [**Dr. Chun Yan Cheung Lectures**](https://www.cs.emory.edu/~cheung/Courses/): ★★★★★ 强推!!!

## Neural Network

- [**Animated AI**](https://animatedai.github.io): ★★★★★ 可视化了以下概念: Convolution, Padding, Stride, 
Groups, Depthwise, Depthwise-Separable, Pixel shuffle. 图像处理肯定会用到.

- [**YOLO V1 Bilibili 讲解**](https://www.bilibili.com/video/BV1gKwAeWEo4?spm_id_from=333.788.videopod.episodes&vd_source=42579e22289b6144ba0b2bdcf99834e3): ★★★★★ 非常清楚, 强推.

- [**A Gentle Introduction to GNN**](https://distill.pub/2021/gnn-intro/): 图神经网络入门.
    - [**Understanding Convolutions on Graphs**](https://distill.pub/2021/understanding-gnns/)

- [**word2vec**](https://www.youtube.com/watch?v=viZrOnJclY0): ★★★★☆ Youtube 视频, 讲解了 word2vec 的原理.

## FPGA 理论

- [**HDLBits**](https://hdlbits.01xz.net/wiki/Main_Page): ★★★★★ 一个在线的 HDL 练习网站. 如果你对 verilog 一无所知, 直接上这个网站绝对没错.

- [**Chisel Bootcamp**](https://mybinder.org/): ★★☆☆☆ 可通过在线的练习来学习 Chisel 语言 (只需做前几章即可)

- [**FPGA**](https://github.com/LeiWang1999/FPGA?tab=readme-ov-file): ★☆☆☆☆ 用来学习 FPGA 的资料库.
    - [Verilog 语法 (Artix7修炼秘籍)](https://leiblog.wang/static/FPGA/books/00《Artix7修炼秘籍》-MIA701第一季.pdf)

- [**FPGA: Architecture, Programmability and Advantageous**](https://www.youtube.com/watch?v=ahws--oNpBc&list=PLXHMvqUANAFOviU0J8HSp0E91lLJInzX1&index=1): ★★★★☆ 一个讲解 FPGA 结构的视频, 很清楚.

## HLS Design FPGA 并行编程

- [**Parallel Programming for FPGAs**](https://kastner.ucsd.edu/hlsbook/): ★★★★☆ Xilinx 研究院的 Steve 首席工程师与 UCSD 的 Ryan Kastner 教授团队合作, 推出了这本开源书, 全书通过 10 个算法实现案例完整的介绍了通过 HLS 工具利用 C/C++ 语言快速实现高性能 FPGA 实现的过程.
    - [**FPGA 并行编程中文版**](https://xupsh.github.io/pp4fpgas-cn/01-Introduction.html), [**中文版 github repo**](https://github.com/xupsh/pp4fpgas-cn?tab=readme-ov-file)


## GPU

- [**tiny-gpu**](https://github.com/adam-maj/tiny-gpu): ★★☆☆☆ 一个小型的 GPU 实现.

- [**VeriGPU**](https://github.com/hughperkins/VeriGPU): ★☆☆☆☆ 一个复杂点的 GPU 实现, 不适合用来入门.

- [**Stanford CS336**](https://www.youtube.com/watch?v=6OBtO9niT00&list=PLoROMvodv4rOY23Y0BoGoBGgQ1zmU_MT_&index=5): ★★★★★ Stanford 的 Language Modeling from Scratch 课程.